Ext.define('TypeAhead.store.TokenStore', {
    extend: 'Ext.data.Store',
    fields: ['token'],
    data: [
        { token: 'Adelanto' },
        { token: 'Agoura Hills' },
        { token: 'Alameda' },
        { token: 'Albany' },
        { token: 'Alhambra' },
        { token: 'Aliso Viejo' },
        { token: 'Alturas' },
        { token: 'Amador City' },
        { token: 'American Canyon' },
        { token: 'Anaheim' },
        { token: 'Anderson' },
        { token: 'Angels Camp' },
        { token: 'Antioch' },
        { token: 'Apple Valley' },
        { token: 'Arcadia' },
        { token: 'Arcata' },
        { token: 'Arroyo Grande' },
        { token: 'Artesia' },
        { token: 'Arvin' },
        { token: 'Atascadero' },
        { token: 'Atherton' },
        { token: 'Atwater' },
        { token: 'Auburn' },
        { token: 'Avalon' },
        { token: 'Avenal' },
        { token: 'Azusa' },
        { token: 'Bakersfield' },
        { token: 'Baldwin Park' },
        { token: 'Banning' },
        { token: 'Barstow' },
        { token: 'Beaumont' },
        { token: 'Bell' },
        { token: 'Bell Gardens' },
        { token: 'Bellflower' },
        { token: 'Belmont' },
        { token: 'Belvedere' },
        { token: 'Benicia' },
        { token: 'Berkeley' },
        { token: 'Beverly Hills' },
        { token: 'Big Bear Lake' },
        { token: 'Biggs' },
        { token: 'Bishop' },
        { token: 'Blue Lake' },
        { token: 'Blythe' },
        { token: 'Bradbury' },
        { token: 'Brawley' },
        { token: 'Brea' },
        { token: 'Brentwood' },
        { token: 'Brisbane' },
        { token: 'Buellton' },
        { token: 'Buena Park' },
        { token: 'Burbank' },
        { token: 'Burlingame' },
        { token: 'Calabasas' },
        { token: 'Calexico' },
        { token: 'California City' },
        { token: 'Calimesa' },
        { token: 'Calipatria' },
        { token: 'Calistoga' },
        { token: 'Camarillo' },
        { token: 'Campbell' },
        { token: 'Canyon Lake' },
        { token: 'Capitola' },
        { token: 'Carlsbad' },
        { token: 'Carmel-by-the-Sea' },
        { token: 'Carpinteria' },
        { token: 'Carson' },
        { token: 'Cathedral City' },
        { token: 'Ceres' },
        { token: 'Cerritos' },
        { token: 'Chico' },
        { token: 'Chino' },
        { token: 'Chino Hills' },
        { token: 'Chowchilla' },
        { token: 'Chula Vista' },
        { token: 'Citrus Heights' },
        { token: 'Claremont' },
        { token: 'Clayton' },
        { token: 'Clearlake' },
        { token: 'Cloverdale' },
        { token: 'Clovis' },
        { token: 'Coachella' },
        { token: 'Coalinga' },
        { token: 'Colfax' },
        { token: 'Colma' },
        { token: 'Colton' },
        { token: 'Colusa' },
        { token: 'Commerce' },
        { token: 'Compton' },
        { token: 'Concord' },
        { token: 'Corcoran' },
        { token: 'Corning' },
        { token: 'Corona' },
        { token: 'Coronado' },
        { token: 'Corte Madera' },
        { token: 'Costa Mesa' },
        { token: 'Cotati' },
        { token: 'Covina' },
        { token: 'Crescent City' },
        { token: 'Cudahy' },
        { token: 'Culver City' },
        { token: 'Cupertino' },
        { token: 'Cypress' },
        { token: 'Daly City' },
        { token: 'Dana Point' },
        { token: 'Danville' },
        { token: 'Davis' },
        { token: 'Del Mar' },
        { token: 'Del Rey Oaks' },
        { token: 'Delano' },
        { token: 'Desert Hot Springs' },
        { token: 'Diamond Bar' },
        { token: 'Dinuba' },
        { token: 'Dixon' },
        { token: 'Dorris' },
        { token: 'Dos Palos' },
        { token: 'Downey' },
        { token: 'Duarte' },
        { token: 'Dublin' },
        { token: 'Dunsmuir' },
        { token: 'East Palo Alto' },
        { token: 'Eastvale' },
        { token: 'El Cajon' },
        { token: 'El Centro' },
        { token: 'El Cerrito' },
        { token: 'El Monte' },
        { token: 'El Segundo' },
        { token: 'Elk Grove' },
        { token: 'Emeryville' },
        { token: 'Encinitas' },
        { token: 'Escalon' },
        { token: 'Escondido' },
        { token: 'Etna' },
        { token: 'Eureka' },
        { token: 'Exeter' },
        { token: 'Fairfax' },
        { token: 'Fairfield' },
        { token: 'Farmersville' },
        { token: 'Ferndale' },
        { token: 'Fillmore' },
        { token: 'Firebaugh' },
        { token: 'Folsom' },
        { token: 'Fontana' },
        { token: 'Fort Bragg' },
        { token: 'Fort Jones' },
        { token: 'Fortuna' },
        { token: 'Foster City' },
        { token: 'Fountain Valley' },
        { token: 'Fowler' },
        { token: 'Fremont' },
        { token: 'Fresno' },
        { token: 'Fullerton' },
        { token: 'Galt' },
        { token: 'Garden Grove' },
        { token: 'Gardena' },
        { token: 'Gilroy' },
        { token: 'Glendale' },
        { token: 'Glendora' },
        { token: 'Goleta' },
        { token: 'Gonzales' },
        { token: 'Grand Terrace' },
        { token: 'Grass Valley' },
        { token: 'Greenfield' },
        { token: 'Gridley' },
        { token: 'Grover Beach' },
        { token: 'Guadalupe' },
        { token: 'Gustine' },
        { token: 'Half Moon Bay' },
        { token: 'Hanford' },
        { token: 'Hawaiian Gardens' },
        { token: 'Hawthorne' },
        { token: 'Hayward' },
        { token: 'Healdsburg' },
        { token: 'Hemet' },
        { token: 'Hercules' },
        { token: 'Hermosa Beach' },
        { token: 'Hesperia' },
        { token: 'Hidden Hills' },
        { token: 'Highland' },
        { token: 'Hillsborough' },
        { token: 'Hollister' },
        { token: 'Holtville' },
        { token: 'Hughson' },
        { token: 'Huntington Beach' },
        { token: 'Huntington Park' },
        { token: 'Huron' },
        { token: 'Imperial' },
        { token: 'Imperial Beach' },
        { token: 'Indian Wells' },
        { token: 'Indio' },
        { token: 'Industry' },
        { token: 'Inglewood' },
        { token: 'Ione' },
        { token: 'Irvine' },
        { token: 'Irwindale' },
        { token: 'Isleton' },
        { token: 'Jackson' },
        { token: 'Jurupa Valley' },
        { token: 'Kerman' },
        { token: 'King City' },
        { token: 'Kingsburg' },
        { token: 'La Cañada Flintridge' },
        { token: 'La Habra' },
        { token: 'La Habra Heights' },
        { token: 'La Mesa' },
        { token: 'La Mirada' },
        { token: 'La Palma' },
        { token: 'La Puente' },
        { token: 'La Quinta' },
        { token: 'La Verne' },
        { token: 'Lafayette' },
        { token: 'Laguna Beach' },
        { token: 'Laguna Hills' },
        { token: 'Laguna Niguel' },
        { token: 'Laguna Woods' },
        { token: 'Lake Elsinore' },
        { token: 'Lake Forest' },
        { token: 'Lakeport' },
        { token: 'Lakewood' },
        { token: 'Lancaster' },
        { token: 'Larkspur' },
        { token: 'Lathrop' },
        { token: 'Lawndale' },
        { token: 'Lemon Grove' },
        { token: 'Lemoore' },
        { token: 'Lincoln' },
        { token: 'Lindsay' },
        { token: 'Live Oak' },
        { token: 'Livermore' },
        { token: 'Livingston' },
        { token: 'Lodi' },
        { token: 'Loma Linda' },
        { token: 'Lomita' },
        { token: 'Lompoc' },
        { token: 'Long Beach' },
        { token: 'Loomis' },
        { token: 'Los Alamitos' },
        { token: 'Los Altos' },
        { token: 'Los Altos Hills' },
        { token: 'Los Angeles' },
        { token: 'Los Banos' },
        { token: 'Los Gatos' },
        { token: 'Loyalton' },
        { token: 'Lynwood' },
        { token: 'Madera' },
        { token: 'Malibu' },
        { token: 'Mammoth Lakes' },
        { token: 'Manhattan Beach' },
        { token: 'Manteca' },
        { token: 'Maricopa' },
        { token: 'Marina' },
        { token: 'Martinez' },
        { token: 'Marysville' },
        { token: 'Maywood' },
        { token: 'McFarland' },
        { token: 'Mendota' },
        { token: 'Menifee' },
        { token: 'Menlo Park' },
        { token: 'Merced' },
        { token: 'Mill Valley' },
        { token: 'Millbrae' },
        { token: 'Milpitas' },
        { token: 'Mission Viejo' },
        { token: 'Modesto' },
        { token: 'Monrovia' },
        { token: 'Montague' },
        { token: 'Montclair' },
        { token: 'Monte Sereno' },
        { token: 'Montebello' },
        { token: 'Monterey' },
        { token: 'Monterey Park' },
        { token: 'Moorpark' },
        { token: 'Moraga' },
        { token: 'Moreno Valley' },
        { token: 'Morgan Hill' },
        { token: 'Morro Bay' },
        { token: 'Mount Shasta' },
        { token: 'Mountain View' },
        { token: 'Murrieta' },
        { token: 'Napa' },
        { token: 'National City' },
        { token: 'Needles' },
        { token: 'Nevada City' },
        { token: 'Newark' },
        { token: 'Newman' },
        { token: 'Newport Beach' },
        { token: 'Norco' },
        { token: 'Norwalk' },
        { token: 'Novato' },
        { token: 'Oakdale' },
        { token: 'Oakland' },
        { token: 'Oakley' },
        { token: 'Oceanside' },
        { token: 'Ojai' },
        { token: 'Ontario' },
        { token: 'Orange' },
        { token: 'Orange Cove' },
        { token: 'Orinda' },
        { token: 'Orland' },
        { token: 'Oroville' },
        { token: 'Oxnard' },
        { token: 'Pacific Grove' },
        { token: 'Pacifica' },
        { token: 'Palm Desert' },
        { token: 'Palm Springs' },
        { token: 'Palmdale' },
        { token: 'Palo Alto' },
        { token: 'Palos Verdes Estates' },
        { token: 'Paradise' },
        { token: 'Paramount' },
        { token: 'Parlier' },
        { token: 'Pasadena' },
        { token: 'Paso Robles' },
        { token: 'Patterson' },
        { token: 'Perris' },
        { token: 'Petaluma' },
        { token: 'Pico Rivera' },
        { token: 'Piedmont' },
        { token: 'Pinole' },
        { token: 'Pismo Beach' },
        { token: 'Pittsburg' },
        { token: 'Placentia' },
        { token: 'Placerville' },
        { token: 'Pleasant Hill' },
        { token: 'Pleasanton' },
        { token: 'Plymouth' },
        { token: 'Point Arena' },
        { token: 'Pomona' },
        { token: 'Port Hueneme' },
        { token: 'Porterville' },
        { token: 'Portola' },
        { token: 'Portola Valley' },
        { token: 'Poway' },
        { token: 'Rancho Cordova' },
        { token: 'Rancho Cucamonga' },
        { token: 'Rancho Mirage' },
        { token: 'Rancho Palos Verdes' },
        { token: 'Rancho Santa Margarita' },
        { token: 'Red Bluff' },
        { token: 'Redding' },
        { token: 'Redlands' },
        { token: 'Redondo Beach' },
        { token: 'Redwood City' },
        { token: 'Reedley' },
        { token: 'Rialto' },
        { token: 'Richmond' },
        { token: 'Ridgecrest' },
        { token: 'Rio Dell' },
        { token: 'Rio Vista' },
        { token: 'Ripon' },
        { token: 'Riverbank' },
        { token: 'Riverside' },
        { token: 'Rocklin' },
        { token: 'Rohnert Park' },
        { token: 'Rolling Hills' },
        { token: 'Rolling Hills Estates' },
        { token: 'Rosemead' },
        { token: 'Roseville' },
        { token: 'Ross' },
        { token: 'Sacramento' },
        { token: 'Salinas' },
        { token: 'San Anselmo' },
        { token: 'San Bernardino' },
        { token: 'San Bruno' },
        { token: 'San Carlos' },
        { token: 'San Clemente' },
        { token: 'San Diego' },
        { token: 'San Dimas' },
        { token: 'San Fernando' },
        { token: 'San Francisco' },
        { token: 'San Gabriel' },
        { token: 'San Jacinto' },
        { token: 'San Joaquin' },
        { token: 'San Jose' },
        { token: 'San Juan Bautista' },
        { token: 'San Juan Capistrano' },
        { token: 'San Leandro' },
        { token: 'San Luis Obispo' },
        { token: 'San Marcos' },
        { token: 'San Marino' },
        { token: 'San Mateo' },
        { token: 'San Pablo' },
        { token: 'San Rafael' },
        { token: 'San Ramon' },
        { token: 'Sand City' },
        { token: 'Sanger' },
        { token: 'Santa Ana' },
        { token: 'Santa Barbara' },
        { token: 'Santa Clara' },
        { token: 'Santa Clarita' },
        { token: 'Santa Cruz' },
        { token: 'Santa Fe Springs' },
        { token: 'Santa Maria' },
        { token: 'Santa Monica' },
        { token: 'Santa Paula' },
        { token: 'Santa Rosa' },
        { token: 'Santee' },
        { token: 'Saratoga' },
        { token: 'Sausalito' },
        { token: 'Scotts Valley' },
        { token: 'Seal Beach' },
        { token: 'Seaside' },
        { token: 'Sebastopol' },
        { token: 'Selma' },
        { token: 'Shafter' },
        { token: 'Shasta Lake' },
        { token: 'Sierra Madre' },
        { token: 'Signal Hill' },
        { token: 'Simi Valley' },
        { token: 'Solana Beach' },
        { token: 'Soledad' },
        { token: 'Solvang' },
        { token: 'Sonoma' },
        { token: 'Sonora' },
        { token: 'South El Monte' },
        { token: 'South Gate' },
        { token: 'South Lake Tahoe' },
        { token: 'South Pasadena' },
        { token: 'South San Francisco' },
        { token: 'St. Helena' },
        { token: 'Stanton' },
        { token: 'Stockton' },
        { token: 'Suisun City' },
        { token: 'Sunnyvale' },
        { token: 'Susanville' },
        { token: 'Sutter Creek' },
        { token: 'Taft' },
        { token: 'Tehachapi' },
        { token: 'Tehama' },
        { token: 'Temecula' },
        { token: 'Temple City' },
        { token: 'Thousand Oaks' },
        { token: 'Tiburon' },
        { token: 'Torrance' },
        { token: 'Tracy' },
        { token: 'Trinidad' },
        { token: 'Truckee' },
        { token: 'Tulare' },
        { token: 'Tulelake' },
        { token: 'Turlock' },
        { token: 'Tustin' },
        { token: 'Twentynine Palms' },
        { token: 'Ukiah' },
        { token: 'Union City' },
        { token: 'Upland' },
        { token: 'Vacaville' },
        { token: 'Vallejo' },
        { token: 'Ventura' },
        { token: 'Vernon' },
        { token: 'Victorville' },
        { token: 'Villa Park' },
        { token: 'Visalia' },
        { token: 'Vista' },
        { token: 'Walnut' },
        { token: 'Walnut Creek' },
        { token: 'Wasco' },
        { token: 'Waterford' },
        { token: 'Watsonville' },
        { token: 'Weed' },
        { token: 'West Covina' },
        { token: 'West Hollywood' },
        { token: 'West Sacramento' },
        { token: 'Westlake Village' },
        { token: 'Westminster' },
        { token: 'Westmorland' },
        { token: 'Wheatland' },
        { token: 'Whittier' },
        { token: 'Wildomar' },
        { token: 'Williams' },
        { token: 'Willits' },
        { token: 'Willows' },
        { token: 'Windsor' },
        { token: 'Winters' },
        { token: 'Woodlake' },
        { token: 'Woodland' },
        { token: 'Woodside' },
        { token: 'Yorba Linda' },
        { token: 'Yountville' },
        { token: 'Yreka' },
        { token: 'Yuba City' },
        { token: 'Yucaipa' },
        { token: 'Yucca Valley' }
    ]
});